export default {
  // change selected post
  CHANGE_SELECTED_POST: 'CHANGE_SELECTED_POST',
  CHANGE_SELECTED_TOPIC: 'CHANGE_SELECTED_TOPIC',

  // actions fetching topics
  START_TO_GET_TOPICS: 'START_TO_GET_TOPICS',
  ERROR_TO_GET_TOPICS: 'ERROR_TO_GET_TOPICS',
  GET_TOPICS: 'GET_TOPICS',

  // actions fetching a full topic
  START_TO_GET_A_FULL_TOPIC: 'START_TO_GET_A_FULL_TOPIC',
  ERROR_TO_GET_A_FULL_TOPIC: 'ERROR_TO_GET_A_FULL_TOPIC',
  GET_A_FULL_TOPIC: 'GET_A_FULL_TOPIC',

  // actions fetching posts
  START_TO_GET_POSTS: 'START_TO_GET_POSTS',
  ERROR_TO_GET_POSTS: 'ERROR_TO_GET_POSTS',
  GET_EDITOR_PICKED_POSTS: 'G∂ET_EDITOR_PICKED_POSTS',
  GET_LISTED_POSTS: 'GET_LISTED_POSTS',
  ERROR_TO_GET_LISTED_POSTS: 'ERROR_TO_GET_LISTED_POSTS',
  ERROR_TO_GET_EDITOR_PICKED_POSTS: 'ERROR_TO_GET_EDITOR_PICKED_POSTS',

  // actions fetching a full post
  START_TO_GET_A_FULL_POST: 'START_TO_GET_A_FULL_POST',
  ERROR_TO_GET_A_FULL_POST: 'ERROR_TO_GET_A_FULL_POST',
  GET_A_FULL_POST: 'GET_A_FULL_POST',

  // actions on index page
  GET_TOPICS_FOR_INDEX_PAGE: 'GET_TOPICS_FOR_INDEX_PAGE',
  GET_PHOTOGRAPHY_POSTS_FOR_INDEX_PAGE: 'GET_PHOTOGRAPHY_POSTS_FOR_INDEX_PAGE',
  GET_INFOGRAPHIC_POSTS_FOR_INDEX_PAGE: 'GET_INFOGRAPHIC_POSTS_FOR_INDEX_PAGE',
  GET_CONTENT_FOR_INDEX_PAGE: 'GET_CONTENT_FOR_INDEX_PAGE',
  START_TO_GET_INDEX_PAGE_CONTENT: 'START_TO_GET_INDEX_PAGE_CONTENT',
  ERROR_TO_GET_INDEX_PAGE_CONTENT: 'ERROR_TO_GET_INDEX_PAGE_CONTENT',

  FETCH_TOPIC_REQUEST: 'FETCH_TOPIC_REQUEST',
  FETCH_TOPIC_SUCCESS: 'FETCH_TOPIC_SUCCESS',
  FETCH_TOPIC_FAILURE: 'FETCH_TOPIC_FAILURE',

  FETCH_TAGS_REQUEST: 'FETCH_TAGS_REQUEST',
  FETCH_TAGS_SUCCESS: 'FETCH_TAGS_SUCCESS',
  FETCH_TAGS_FAILURE: 'FETCH_TAGS_FAILURE',

  FETCH_CATEGORIES_REQUEST: 'FETCH_CATEGORIES_REQUEST',
  FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
  FETCH_CATEGORIES_FAILURE: 'FETCH_CATEGORIES_FAILURE',

  FETCH_ARTICLE_REQUEST: 'FETCH_ARTICLE_REQUEST',
  FETCH_ARTICLE_SUCCESS: 'FETCH_ARTICLE_SUCCESS',
  FETCH_ARTICLE_FAILURE: 'FETCH_ARTICLE_FAILURE',

  FETCH_RELATED_ARTICLES_REQUEST: 'FETCH_RELATED_ARTICLES_REQUEST',
  FETCH_RELATED_ARTICLES_SUCCESS: 'FETCH_RELATED_ARTICLES_SUCCESS',
  FETCH_RELATED_ARTICLES_FAILURE: 'FETCH_RELATED_ARTICLES_FAILURE',

  FETCH_ARTICLES_BY_GROUP_UUID_REQUEST: 'FETCH_ARTICLES_BY_GROUP_UUID_REQUEST',
  FETCH_ARTICLES_BY_GROUP_UUID_SUCCESS: 'FETCH_ARTICLES_BY_GROUP_UUID_SUCCESS',
  FETCH_ARTICLES_BY_GROUP_UUID_FAILURE: 'FETCH_ARTICLES_BY_GROUP_UUID_FAILURE',

  FETCH_AUTHOR_DETAILS_REQUEST: 'FETCH_AUTHOR_DETAILS_REQUEST',
  FETCH_AUTHOR_DETAILS_SUCCESS: 'FETCH_AUTHOR_DETAILS_SUCCESS',
  FETCH_AUTHOR_DETAILS_FAILURE: 'FETCH_AUTHOR_DETAILS_FAILURE',

  SEARCH_AUTHORS_REQUEST: 'SEARCH_AUTHORS_REQUEST',
  SEARCH_AUTHORS_SUCCESS: 'SEARCH_AUTHORS_SUCCESS',
  SEARCH_AUTHORS_FAILURE: 'SEARCH_AUTHORS_FAILURE',

  LIST_ALL_AUTHORS_REQUEST: 'LIST_ALL_AUTHORS_REQUEST',
  LIST_ALL_AUTHORS_SUCCESS: 'LIST_ALL_AUTHORS_SUCCESS',
  LIST_ALL_AUTHORS_FAILURE: 'LIST_ALL_AUTHORS_FAILURE',

  FETCH_AUTHOR_COLLECTION_REQUEST: 'FETCH_AUTHOR_COLLECTION_REQUEST',
  FETCH_AUTHOR_COLLECTION_FAILURE: 'FETCH_AUTHOR_COLLECTION_FAILURE',
  FETCH_AUTHOR_COLLECTION_SUCCESS: 'FETCH_AUTHOR_COLLECTION_SUCCESS',

  FETCH_FEATURE_ARTICLES_REQUEST: 'FETCH_FEATURE_ARTICLES_REQUEST',
  FETCH_FEATURE_ARTICLES_SUCCESS: 'FETCH_FEATURE_ARTICLES_SUCCESS',
  FETCH_FEATURE_ARTICLES_FAILURE: 'FETCH_FEATURE_ARTICLES_FAILURE',

  SET_ARTICLE_TOPIC_LIST: 'SET_ARTICLE_TOPIC_LIST',
  SET_BOOKMARKS_OF_LONGFORM_ARTICLE: 'SET_BOOKMARKS_OF_LONGFORM_ARTICLE',
  SET_HEADER_INFO: 'SET_HEADER_INFO',
  SET_PAGE_TITLE: 'SET_PAGE_TITLE',
  SET_PAGE_THEME: 'SET_PAGE_THEME',
  SET_PAGE_TYPE: 'SET_PAGE_TYPE',
  SET_PROGRESS_PRECENTAGE: 'SET_PROGRESS_PRECENTAGE',

  SET_ARTICLE_TOOLS: 'SET_ARTICLE_TOOLS',

  SET_NEXT_POPUP_TIME_STAMP: 'SET_NEXT_POPUP_TIME_STAMP',

  singleBookmark: {
    read: {
      request: 'request to fetch single bookmark',
      success: 'succes to fetch single bookmark',
      failure: 'fail to fetch single bookmark',
    },
    create: {
      request: 'request to  create single bookmark',
      success: 'succes to create single bookmark',
      failure: 'fail to create single bookmark',
    },
    delete: {
      request: 'request to  delete single bookmark',
      success: 'succes to delete single bookmark',
      failure: 'fail to delete single bookmark',
    },
  },

  multipleBookMarks: {
    read: {
      request: 'request to fetch multiple bookmarks',
      success: 'succes to fetch multiple bookmarks',
      failure: 'fail to fetch multiple bookmarks',
    },
  },
}
