const types = {
  // change selected post
  CHANGE_SELECTED_POST: 'CHANGE_SELECTED_POST',

  CHANGE_SELECTED_TOPIC: 'CHANGE_SELECTED_TOPIC',

  // actions fetching topics
  START_TO_GET_TOPICS: 'START_TO_GET_TOPICS',

  ERROR_TO_GET_TOPICS: 'ERROR_TO_GET_TOPICS',

  GET_TOPICS: 'GET_TOPICS',

  // actions fetching a full topic
  START_TO_GET_A_FULL_TOPIC: 'START_TO_GET_A_FULL_TOPIC',

  ERROR_TO_GET_A_FULL_TOPIC: 'ERROR_TO_GET_A_FULL_TOPIC',

  GET_A_FULL_TOPIC: 'GET_A_FULL_TOPIC',

  // actions fetching posts
  START_TO_GET_POSTS: 'START_TO_GET_POSTS',

  ERROR_TO_GET_POSTS: 'ERROR_TO_GET_POSTS',

  GET_EDITOR_PICKED_POSTS: 'GET_EDITOR_PICKED_POSTS',

  GET_LISTED_POSTS: 'GET_LISTED_POSTS',

  ERROR_TO_GET_LISTED_POSTS: 'ERROR_TO_GET_LISTED_POSTS',

  ERROR_TO_GET_EDITOR_PICKED_POSTS: 'ERROR_TO_GET_EDITOR_PICKED_POSTS',

  // actions fetching a full post
  START_TO_GET_A_FULL_POST: 'START_TO_GET_A_FULL_POST',

  ERROR_TO_GET_A_FULL_POST: 'ERROR_TO_GET_A_FULL_POST',

  GET_A_FULL_POST: 'GET_A_FULL_POST',

  // actions on index page
  GET_TOPICS_FOR_INDEX_PAGE: 'GET_TOPICS_FOR_INDEX_PAGE',

  GET_PHOTOGRAPHY_POSTS_FOR_INDEX_PAGE: 'GET_PHOTOGRAPHY_POSTS_FOR_INDEX_PAGE',

  GET_INFOGRAPHIC_POSTS_FOR_INDEX_PAGE: 'GET_INFOGRAPHIC_POSTS_FOR_INDEX_PAGE',

  GET_CONTENT_FOR_INDEX_PAGE: 'GET_CONTENT_FOR_INDEX_PAGE',

  START_TO_GET_INDEX_PAGE_CONTENT: 'START_TO_GET_INDEX_PAGE_CONTENT',

  ERROR_TO_GET_INDEX_PAGE_CONTENT: 'ERROR_TO_GET_INDEX_PAGE_CONTENT',

}

export default types
